(function(){function aa(){this.setSettings=function(a){for(var c=0;24>c;c++)this[String.fromCharCode(97+c)]=a[c]||0;.01>this.c&&(this.c=.01);a=this.b+this.c+this.e;.18>a&&(a=.18/a,this.b*=a,this.c*=a,this.e*=a)}}void 0===Date.now&&(Date.now=function(){return(new Date).valueOf()});var f=f||function(){var a=[];return{REVISION:"14",getAll:function(){return a},removeAll:function(){a=[]},add:function(c){a.push(c)},remove:function(c){c=a.indexOf(c);-1!==c&&a.splice(c,1)},update:function(c){if(0===a.length)return!1;
var b=0;for(c=void 0!==c?c:"undefined"!=typeof window&&void 0!==window.performance&&void 0!==window.performance.now?window.performance.now():Date.now();b<a.length;)a[b].update(c)?b++:a.splice(b,1);return!0}}}();f.Tween=function(a){var c={},b={},e={},g=1E3,k=0,d=!1,q=!1,ba=0,h=null,s=f.Easing.Linear.None,w=f.Interpolation.Linear,N=[],t=null,l=!1,u=null,ca=null,m=null,v;for(v in a)c[v]=parseFloat(a[v],10);this.to=function(a,e){return void 0!==e&&(g=e),b=a,this};this.start=function(g){f.add(this);q=
!0;l=!1;h=void 0!==g?g:"undefined"!=typeof window&&void 0!==window.performance&&void 0!==window.performance.now?window.performance.now():Date.now();h+=ba;for(var k in b){if(b[k]instanceof Array){if(0===b[k].length)continue;b[k]=[a[k]].concat(b[k])}c[k]=a[k];0==c[k]instanceof Array&&(c[k]*=1);e[k]=c[k]||0}return this};this.stop=function(){return q?(f.remove(this),q=!1,null!==m&&m.call(a),this.stopChainedTweens(),this):this};this.stopChainedTweens=function(){for(var a=0,b=N.length;a<b;a++)N[a].stop()};
this.delay=function(a){return ba=a,this};this.repeat=function(a){return k=a,this};this.yoyo=function(a){return d=a,this};this.easing=function(a){return s=a,this};this.interpolation=function(a){return w=a,this};this.chain=function(){return N=arguments,this};this.onStart=function(a){return t=a,this};this.onUpdate=function(a){return u=a,this};this.onComplete=function(a){return ca=a,this};this.onStop=function(a){return m=a,this};this.update=function(q){var f;if(q<h)return!0;!1===l&&(null!==t&&t.call(a),
l=!0);var m=(q-h)/g,m=1<m?1:m,v=s(m);for(f in b){var p=c[f]||0,r=b[f];r instanceof Array?a[f]=w(r,v):("string"==typeof r&&(r=p+parseFloat(r,10)),"number"==typeof r&&(a[f]=p+(r-p)*v))}null!==u&&u.call(a,v);if(1==m){if(0<k){isFinite(k)&&k--;for(f in e)"string"==typeof b[f]&&(e[f]+=parseFloat(b[f],10)),d&&(m=e[f],e[f]=b[f],b[f]=m),c[f]=e[f];return h=q+ba,!0}null!==ca&&ca.call(a);f=0;for(m=N.length;f<m;f++)N[f].start(q);return!1}return!0}};f.Easing={Linear:{None:function(a){return a}},Quadratic:{In:function(a){return a*
a},Out:function(a){return a*(2-a)},InOut:function(a){return 1>(a*=2)?.5*a*a:-.5*(--a*(a-2)-1)}},Cubic:{In:function(a){return a*a*a},Out:function(a){return--a*a*a+1},InOut:function(a){return 1>(a*=2)?.5*a*a*a:.5*((a-=2)*a*a+2)}},Quartic:{In:function(a){return a*a*a*a},Out:function(a){return 1- --a*a*a*a},InOut:function(a){return 1>(a*=2)?.5*a*a*a*a:-.5*((a-=2)*a*a*a-2)}},Quintic:{In:function(a){return a*a*a*a*a},Out:function(a){return--a*a*a*a*a+1},InOut:function(a){return 1>(a*=2)?.5*a*a*a*a*a:.5*
((a-=2)*a*a*a*a+2)}},Sinusoidal:{In:function(a){return 1-Math.cos(a*Math.PI/2)},Out:function(a){return Math.sin(a*Math.PI/2)},InOut:function(a){return.5*(1-Math.cos(Math.PI*a))}},Exponential:{In:function(a){return 0===a?0:Math.pow(1024,a-1)},Out:function(a){return 1===a?1:1-Math.pow(2,-10*a)},InOut:function(a){return 0===a?0:1===a?1:1>(a*=2)?.5*Math.pow(1024,a-1):.5*(-Math.pow(2,-10*(a-1))+2)}},Circular:{In:function(a){return 1-Math.sqrt(1-a*a)},Out:function(a){return Math.sqrt(1- --a*a)},InOut:function(a){return 1>
(a*=2)?-.5*(Math.sqrt(1-a*a)-1):.5*(Math.sqrt(1-(a-=2)*a)+1)}},Elastic:{In:function(a){var c,b=.1;return 0===a?0:1===a?1:(!b||1>b?(b=1,c=.1):c=.4*Math.asin(1/b)/(2*Math.PI),-(b*Math.pow(2,10*(a-=1))*Math.sin(2*(a-c)*Math.PI/.4)))},Out:function(a){var c,b=.1;return 0===a?0:1===a?1:(!b||1>b?(b=1,c=.1):c=.4*Math.asin(1/b)/(2*Math.PI),b*Math.pow(2,-10*a)*Math.sin(2*(a-c)*Math.PI/.4)+1)},InOut:function(a){var c,b=.1;return 0===a?0:1===a?1:(!b||1>b?(b=1,c=.1):c=.4*Math.asin(1/b)/(2*Math.PI),1>(a*=2)?-.5*
b*Math.pow(2,10*(a-=1))*Math.sin(2*(a-c)*Math.PI/.4):b*Math.pow(2,-10*(a-=1))*Math.sin(2*(a-c)*Math.PI/.4)*.5+1)}},Back:{In:function(a){return a*a*(2.70158*a-1.70158)},Out:function(a){return--a*a*(2.70158*a+1.70158)+1},InOut:function(a){return 1>(a*=2)?.5*a*a*(3.5949095*a-2.5949095):.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)}},Bounce:{In:function(a){return 1-f.Easing.Bounce.Out(1-a)},Out:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:
7.5625*(a-=2.625/2.75)*a+.984375},InOut:function(a){return.5>a?.5*f.Easing.Bounce.In(2*a):.5*f.Easing.Bounce.Out(2*a-1)+.5}}};f.Interpolation={Linear:function(a,c){var b=a.length-1,e=b*c,g=Math.floor(e),k=f.Interpolation.Utils.Linear;return 0>c?k(a[0],a[1],e):1<c?k(a[b],a[b-1],b-e):k(a[g],a[g+1>b?b:g+1],e-g)},Bezier:function(a,c){var b=0,e=a.length-1,g=Math.pow,k=f.Interpolation.Utils.Bernstein,d;for(d=0;d<=e;d++)b+=g(1-c,e-d)*g(c,d)*a[d]*k(e,d);return b},CatmullRom:function(a,c){var b=a.length-1,
e=b*c,g=Math.floor(e),k=f.Interpolation.Utils.CatmullRom;return a[0]===a[b]?(0>c&&(g=Math.floor(e=b*(1+c))),k(a[(g-1+b)%b],a[g],a[(g+1)%b],a[(g+2)%b],e-g)):0>c?a[0]-(k(a[0],a[0],a[1],a[1],-e)-a[0]):1<c?a[b]-(k(a[b],a[b],a[b-1],a[b-1],e-b)-a[b]):k(a[g?g-1:0],a[g],a[b<g+1?b:g+1],a[b<g+2?b:g+2],e-g)},Utils:{Linear:function(a,c,b){return(c-a)*b+a},Bernstein:function(a,c){var b=f.Interpolation.Utils.Factorial;return b(a)/b(c)/b(a-c)},Factorial:function(){var a=[1];return function(c){var b=1,e;if(a[c])return a[c];
for(e=c;1<e;e--)b*=e;return a[c]=b}}(),CatmullRom:function(a,c,b,e,g){a=.5*(b-a);e=.5*(e-c);var k=g*g;return(2*c-2*b+a+e)*g*k+(-3*c+3*b-2*a-e)*k+a*g+c}}};var G=new function(){this._params=new aa;var a,c,b,e,g,k,d,q,f,h,m,r;this.reset=function(){var a=this._params;e=100/(a.f*a.f+.001);g=100/(a.g*a.g+.001);k=1-a.h*a.h*a.h*.01;d=-a.i*a.i*a.i*1E-6;a.a||(m=.5-a.n/2,r=5E-5*-a.o);q=1+a.l*a.l*(0<a.l?-.9:10);f=0;h=1==a.m?0:(1-a.m)*(1-a.m)*2E4+32};this.totalReset=function(){this.reset();var e=this._params;
return a=e.b*e.b*1E5,c=e.c*e.c*1E5,b=e.e*e.e*1E5+12,3*((a+c+b)/3|0)};this.synthWave=function(s,t){var l=this._params,u=1!=l.s||l.v,p=l.v*l.v*.1,w=1+3E-4*l.w,v=l.s*l.s*l.s*.1,z=1+1E-4*l.t,A=1!=l.s,D=l.x*l.x,H=l.g,E=l.q||l.r,L=l.r*l.r*l.r*.2,G=l.q*l.q*(0>l.q?-1020:1020),K=l.p?((1-l.p)*(1-l.p)*2E4|0)+32:0,U=l.d,M=l.j/2,X=l.k*l.k*.01,da=l.a,ea=a,Y=1/a,Z=1/c,$=1/b,l=5/(1+l.u*l.u*20)*(.01+v);.8<l&&(l=.8);for(var l=1-l,fa=!1,S=0,O=0,P=0,Q=0,I=0,T,J=0,x,B=0,F,ga=0,n,V=0,C,ha=0,W=Array(1024),R=Array(32),y=
W.length;y--;)W[y]=0;for(y=R.length;y--;)R[y]=2*Math.random()-1;for(y=0;y<t;y++){if(fa)return y;K&&++V>=K&&(V=0,this.reset());h&&++f>=h&&(h=0,e*=q);k+=d;e*=k;e>g&&(e=g,0<H&&(fa=!0));x=e;0<M&&(ha+=X,x*=1+Math.sin(ha)*M);x|=0;8>x&&(x=8);da||(m+=r,0>m?m=0:.5<m&&(m=.5));if(++O>ea)switch(O=0,++S){case 1:ea=c;break;case 2:ea=b}switch(S){case 0:P=O*Y;break;case 1:P=1+2*(1-O*Z)*U;break;case 2:P=1-O*$;break;case 3:P=0,fa=!0}E&&(G+=L,F=G|0,0>F?F=-F:1023<F&&(F=1023));u&&w&&(p*=w,1E-5>p?p=1E-5:.1<p&&(p=.1));
C=0;for(var aa=8;aa--;){B++;if(B>=x&&(B%=x,3==da))for(var ia=R.length;ia--;)R[ia]=2*Math.random()-1;switch(da){case 0:n=B/x<m?.5:-.5;break;case 1:n=1-B/x*2;break;case 2:n=B/x;n=6.28318531*(.5<n?n-1:n);n=1.27323954*n+.405284735*n*n*(0>n?1:-1);n=.225*((0>n?-1:1)*n*n-n)+n;break;case 3:n=R[Math.abs(32*B/x|0)]}u&&(T=J,v*=z,0>v?v=0:.1<v&&(v=.1),A?(I+=(n-J)*v,I*=l):(J=n,I=0),J+=I,Q+=J-T,Q*=1-p,n=Q);E&&(W[ga%1024]=n,n+=W[(ga-F+1024)%1024],ga++);C+=n}C=.125*C*P*D;s[y]=1<=C?32767:-1>=C?-32768:32767*C|0}return t}};
window.jsfxr=function(a){G._params.setSettings(a);var c=G.totalReset();a=new Uint8Array(4*((c+1)/2|0)+44);var c=2*G.synthWave(new Uint16Array(a.buffer,44),c),b=new Uint32Array(a.buffer,0,44);b[0]=1179011410;b[1]=c+36;b[2]=1163280727;b[3]=544501094;b[4]=16;b[5]=65537;b[6]=44100;b[7]=88200;b[8]=1048578;b[9]=1635017060;b[10]=c;for(var c=c+44,b=0,e="data:audio/wav;base64,";b<c;b+=3)var g=a[b]<<16|a[b+1]<<8|a[b+2],e=e+("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g>>18]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g>>
12&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g>>6&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[g&63]);return e};var p="font s_title t_earth t_water t_air t_fire p_mage p_staff e_lasher e_banshee e_imp e_frostgiant bg".split(" "),z="title",w=null,t=!1,r,X,H,K,h,D,s,Y,Z,$,E,S,u,T,L,U,V,m,A,M=document.querySelector("#c"),d=M.getContext("2d");r=function(){var a=p,c=a.length,b={},e=0;return{loadImage:function(a){return img=new Image,img.src="img/"+
a+".png",img.onload=function(){e++;c===e&&(p=b,X=!0)},img},loadImages:function(e){for(e=0;e<c;e++)b[a[e]]=this.loadImage(a[e])},loadAllAssets:function(){var a,b;this.loadImages();a=function(){X?(b=new CustomEvent("imagesLoaded"),document.dispatchEvent(b)):setTimeout(a,100)};setTimeout(a,100)},rand:function(a,b){return Math.random()*(b-a+1)+a},randInt:function(a,b){return Math.random()*(b-a+1)|0+a}}}();H=function(){function a(a){var b=this,c;this.max=a.max;this.tick=0;this.pool=[];a.data.forEach(function(d,
q){c=new Audio;c.src=jsfxr(d);c.loop=a.loop||!1;b.pool.push(c)})}var c=r.randInt,b={earth:{max:1,data:[[3,.14,.35,.18,.62,.12,,,.3,.49,,-.4599,,,-.7,.1839,-.48,-.7576,.22,.34,.48,.56,.04,.5]]},water:{max:1,data:[[2,.11,.38,.25,.87,.3,,.0397,.6799,.0495,.0062,.6,.0332,,.56,.2,-.06,.6,.87,-.4399,.17,.14,-.6,.5]]},air:{max:1,data:[[3,.2,.0505,.1809,.5,.41,,-.0108,.002,-.0133,,.2719,.509,.9626,-.0969,-.5361,.0753,.1552,.9993,-2E-4,.6453,,.2999,.5]]},fire:{max:1,data:[[3,,.2477,.4477,.34,.223,,-.2666,
,,,,,,,,,,1,,,,,.5]]},lasher:{max:1,data:[[1,.0331,.2341,.3025,.293,.5057,,.3536,-.6702,,,-.6175,,,-.047,.5549,.0015,.3833,.285,,-.6082,.0111,.2431,.5]]},imp:{max:1,data:[]},banshee:{max:1,data:[[0,.4,.01,.02,.2699,.5604,,.1673,,,,,,.2157,.02,.72,-.0799,-.86,.9174,,,,,.5]]},frostgiant:{max:1,data:[[2,,.049,.2173,.5542,.5711,,-.1999,-.0045,.0213,.7235,-.0938,.2236,,.4777,.867,.1158,.7062,.7015,.2018,.4116,.0692,.0036,.5]]},stun:{max:1,data:[[0,,.09,.5889,.484,.54,,-.02,,.16,.34,.5637,.6915,,,,,,1,
,,,,.5]]},thud:{max:1,data:[[3,.0122,.1754,.0444,.183,.438,.0156,-.492,.0906,,.03,.0314,.1224,.0381,.053,.083,.1109,-.0124,1,.1502,.1029,.167,-.1358,.5]]},walk:{max:2,data:[[2,,.06,,.1867,.26,.0399,-.567,,,.0174,-.6,.0435,.4974,-.0416,,.0411,.0146,1,-.0205,,.2186,.073,.5],[2,,.5231,.2056,.9019,.264,,-.6485,,.0732,.7339,.8908,-.7222,.9728,-.4364,,-.5954,.1079,.9147,,.22,,.4332,.5]]},menu:{max:1,data:[]}};return{sounds:{},init:function(){for(var e in b)b.hasOwnProperty(e)&&(this.sounds[e]=new a(b[e]))},
play:function(a){a=this.sounds[a];var b=a.pool[1<a.pool.length?c(0,a.pool.length-1):0];b&&b.play();a.tick=a.tick<a.max-1?a.tick+1:0}}}();K=function(){var a=document.createElement("canvas").getContext("2d"),c=[];return{init:function(){var b,e,g;b=p.font;var d=b.width,f=b.height,q,h=0;a.canvas.width=d;a.canvas.height=f;a.drawImage(b,0,0,d,f);q=a.getImageData(0,0,d,f).data;for(b=0;b<q.length;b+=4)e=b/4%d|0,g=b/4/d|0,g===f-1&&!q[b+3]&&(c.push({x:h,y:0,w:e-h,h:f-1}),h=e+1,b+=4)},getData:function(b){var e,
g=b.length,d=[];for(e=0;e<g;e++)d.push(c[b.charCodeAt(e)-32]);return{buffer:a.canvas,word:d}}}}();h=function(){return{init:function(){d.imageSmoothingEnabled=!1;d.oImageSmoothingEnabled=!1;d.mozImageSmoothingEnabled=!1;d.webkitImageSmoothingEnabled=!1;d.globalCompositeOperation="source-over"},drawLine:function(a){d.strokeStyle=a.c;d.lineWidth=1;d.lineCap="square";d.beginPath();"h"===a.o?(d.moveTo(0,a.y),d.lineTo(a.x,a.y)):(d.moveTo(a.x,0),d.lineTo(a.x,a.y));d.stroke()},drawText:function(a){var c=
K.getData(a.text),b=0;c.word.forEach(function(e,g){d.drawImage(c.buffer,e.x,e.y,e.w,e.h,a.x+b,a.y,e.w,e.h);b+=e.w})},fillRect:function(a){d.fillStyle=a.c;d.fillRect(a.x,a.y,a.w,a.h)},segment:function(a,c,b,e,g,d,f){this.polygon(a,c,a+b,c,e+d,g,e,g,f)},polygon:function(a,c,b,e,g,k,f,q,h){d.fillStyle=h;d.beginPath();d.moveTo(a,c);d.lineTo(b,e);d.lineTo(g,k);d.lineTo(f,q);d.closePath();d.fill()}}}();D=function(){function a(a){this.type=c.randInt(0,3);this.colour=e[this.type];this.spell=b[this.type];
this.image=p["t_"+this.spell];this.size=12;this.spacing=1;a&&(this.x=a.x,this.y=a.y,this.screenPos={x:a.x*(this.size+this.spacing),y:a.y*(this.size+this.spacing)},this.newPos={},a.sY&&this.setNewPos({x:a.x,y:a.y,sY:a.sY}))}var c=r,b=["earth","water","air","fire"],e=["green","blue","magenta","red"],g=(d.globalCompositeOperation="screen","screen"===d.globalCompositeOperation);return a.prototype.update=function(a){},a.prototype.render=function(){this.selected?g?(d.drawImage(this.image,this.screenPos.x,
this.screenPos.y,this.size,this.size),d.globalCompositeOperation="screen",d.drawImage(this.image,this.screenPos.x,this.screenPos.y,this.size,this.size),d.globalCompositeOperation="source-over"):d.drawImage(this.image,this.screenPos.x,this.screenPos.y,this.size,this.size):g?d.drawImage(this.image,this.screenPos.x,this.screenPos.y,this.size,this.size):(d.globalAlpha=.75,d.drawImage(this.image,this.screenPos.x,this.screenPos.y,this.size,this.size),d.globalAlpha=1)},a.prototype.setNewPos=function(a){this.x=
a.x;this.y=a.y;a.sY&&(this.screenPos.y+=a.sY*(this.size+this.spacing));this.newPos={x:a.x*(this.size+this.spacing),y:a.y*(this.size+this.spacing)};(new f.Tween(this.screenPos)).to(this.newPos,100).start()},a}();s=function(){var a=new D,c=a.size+a.spacing,b=[];return{x:3,y:53,size:5,numTiles:0,isAnimated:!1,animatedTiles:[],create:function(){var a,b,c=[];for(a=0;a<this.size;a++)for(c[a]=[],b=0;b<this.size;b++)c[a][b]=new D({x:a,y:b}),this.numTiles+=1;return c},createTileAt:function(a){b[a.x][a.y]=
new D(a);this.numTiles+=1},getTileAtCell:function(a){return this.cellInBounds(a)?b[a.x][a.y]:null},getTileAtScreenPos:function(a){return a.x=(a.x-M.offsetLeft)/4,a.y=(a.y-M.offsetTop)/4,this.posInBounds(a)?(a.x-=this.x,a.x/=c,a.y-=this.y,a.y/=c,this.getTileAtCell({x:a.x|0,y:a.y|0})):null},moveTileTo:function(a,c){b[a.x][a.y]=null;b[c.x][c.y]=a;a.setNewPos(c)},removeTileAt:function(a){b[a.x][a.y]=null;this.numTiles-=1},cellInBounds:function(a){return 0<=a.x&&a.x<this.size&&0<=a.y&&a.y<this.size},posInBounds:function(a){return a.x>=
this.x&&a.x<this.x+this.size*c&&a.y>=this.y&&a.y<this.y+this.size*c},validMove:function(a,b){return(b.x===a.x-1||b.x===a.x+1)&&b.y===a.y||(b.y===a.y-1||b.y===a.y+1)&&b.x===a.x},getFarthestPos:function(a){var b;do b=a,a={x:b.x,y:b.y+1};while(this.cellInBounds(a)&&!this.getTileAtCell(a));return b},replaceMatchedTiles:function(){var a,b,c,d,f,h=[];for(a=0;a<this.size;a++)for(h[a]=0,b=this.size-1;0<=b;b--)c={x:a,y:b},(d=this.getTileAtCell(c))?(f=this.getFarthestPos(c),this.moveTileTo(d,f)):h[a]+=1;for(a=
0;a<this.size;a++)for(b=0;b<this.size;b++)c={x:a,y:b},(d=this.getTileAtCell(c))||this.createTileAt({x:a,y:b,sY:-h[a]})},init:function(){b=this.create()},update:function(a){var c;for(a=0;a<this.size;a++)for(c=0;c<this.size;c++)b[a][c]instanceof D&&b[a][c].update()},render:function(){this.drawGrid(this.x-.5,this.y-.5);this.drawTiles(this.x,this.y)},drawGrid:function(a,b){var k=0;d.save();d.scale(4,4);for(d.translate(a,b);k<this.size+1;k++)h.drawLine({o:"v",c:"black",x:k*c,y:this.size*c}),h.drawLine({o:"h",
c:"black",x:this.size*c,y:k*c});d.restore()},drawTiles:function(a,g){d.save();d.scale(4,4);d.translate(a,g);d.rect(0,0,this.size*c,this.size*c);d.clip();for(a=0;a<this.size;a++)for(g=0;g<this.size;g++)b[a][g]instanceof D&&b[a][g].render();d.restore()},flipTiles:!1}}();Y=function(){function a(){this.x=70;this.y=52;this.size={x:8,y:66};this.maxTime=120;this.startTime=null;this.time=0;this.tick=this.size.y/this.maxTime;this.timePenalty=null;this.paused=!1;this.pausedAt=null}return a.prototype.init=function(){this.startTime=
+new Date},a.prototype.update=function(a){this.startTime&&(this.time+=a);this.timePenalty&&this.time>this.timePenalty.end&&(this.timePenalty=null)},a.prototype.render=function(){d.save();d.scale(4,4);d.translate(this.x,this.y);h.fillRect({c:"gray",x:0,y:0,w:this.size.x,h:this.size.y});h.fillRect({c:"black",x:1,y:1,w:this.size.x-2,h:this.size.y-2});this.timePenalty&&(h.fillRect({c:"#267AF6",x:1,y:1+(this.timePenalty.from+this.timePenalty.to|0)*this.tick,w:this.size.x-2,h:this.size.y-2-(this.time|0)*
this.tick}),h.fillRect({c:"red",x:1,y:1+(this.timePenalty.from|0)*this.tick,w:this.size.x-2,h:(this.timePenalty.to|0)*this.tick}));h.fillRect({c:"#267AF6",x:1,y:1+(this.time|0)*this.tick,w:this.size.x-2,h:this.size.y-2-(this.time|0)*this.tick});d.restore()},a.prototype.add=function(a,b){0<this.time-a?this.time-=a:this.time=0;b("+"+a+" SECS")},a.prototype.remove=function(a,b){this.timePenalty={from:this.time+a+.8,to:a,end:this.time};this.time+=a;b("-"+a+" SECS")},a.prototype.pause=function(a){(this.paused=
a)?this.pausedAt=+new Date:this.startTime+=+new Date-this.pausedAt},a}();Z=function(){function a(){this.level=0;this.highestCrit={amount:0,enemy:""};this.mostDamageTaken={amount:0,enemy:""};this.totalTimeSurvived=this.totalEnemiesKilled=this.damageTakenOverall=this.longestSpellChain=0}return a.prototype.update=function(a,b){this.hasOwnProperty(a)&&("number"==typeof b&&b>this[a]?this[a]=b:"object"==typeof b&&b.amount>this[a].amount&&(this[a]=b))},a}();$=function(){function a(){this.step=.25;this.stepTimer=
0;this.mage=p.p_mage;this.mx=38;this.my=11;this.mw=this.mage.width;this.mh=this.mage.height;this.staff=p.p_staff;this.sx=44;this.sy=16;this.sw=this.staff.width;this.sh=this.staff.height;this.rotate=0;this.stats=new c;this.level=1}var c=Z,b=r.randInt;return a.prototype.update=function(a){this.stepTimer+=a;if(this.stepTimer>=2*this.step||t)this.stepTimer=0},a.prototype.render=function(){t?0!==this.rotate?(d.save(),d.translate(0,this.h),d.rotate(this.rotate*Math.PI/180),d.drawImage(this.staff,this.sx+
this.rotate,this.sy-this.rotate+(this.stepTimer>=this.step?1:0),this.sw,this.sh),d.restore()):d.drawImage(this.staff,this.sx,this.sy+(this.stepTimer>=this.step?1:0),this.sw,this.sh):d.drawImage(this.mage,this.mx,this.my+(this.stepTimer>=this.step?1:0),this.mw,this.mh)},a.prototype.hit=function(a){var c=b(0,100)<a.critChance?1:.5;return{crit:1<=c,damage:c*a.strength|0}},a.prototype.castAnimation=function(){var a=this,b=(new f.Tween({r:0})).to({r:-10},200).easing(f.Easing.Quintic.In).onUpdate(function(){a.rotate=
this.r}),c=(new f.Tween({r:-10})).to({r:0},500).easing(f.Easing.Quadratic.Out).onUpdate(function(){a.rotate=this.r});b.chain(c).start()},a}();E=function(){function a(a){var b=this;this.x=a.x;this.y=a.y;this.dY=6*a.dY;this.alpha=1;this.text=a.text;this.lifeSpan=1.2;this.dead=!1;(new f.Tween({y:this.y,alpha:this.alpha})).to({y:this.y+this.dY,alpha:0},1E3*b.lifeSpan).easing(f.Easing.Exponential.In).onUpdate(function(){b.y=this.y;b.alpha=this.alpha}).onComplete(function(){b.dead=!0}).start()}return a.prototype.render=
function(){d.globalAlpha=this.alpha;h.drawText({text:this.text,x:this.x,y:this.y});d.globalAlpha=1},a}();S=function(){function a(a){this.y=this.x=0;this.z=c(300,450);this.fov=60;this.step=.25;this.stepTimer=0;this.type=c(0,b.length-1);this.name=b[this.type].name;this.spell=b[this.type].spell;this.weakTo=b[this.type].weakTo;this.level=a.level;this.health=this.baseHealth=10+4*this.level;this.strength=2*this.level;this.critChance=this.level+10;this.attacking=!1;this.attackFor=0;this.lastAttacked=null;
this.image=p["e_"+this.name];this.w=this.image.width;this.h=this.image.height;this.dead=!1}var c=r.randInt,b=[{name:"lasher",spell:"earth",weakTo:"air"},{name:"imp",spell:"fire",weakTo:"water"},{name:"banshee",spell:"air",weakTo:"earth"},{name:"frostgiant",spell:"water",weakTo:"fire"}];return a.prototype.drawHealthMeter=function(){d.fillStyle="white";d.fillRect(2,2,20,4);d.fillStyle="black";d.fillRect(3,3,18,2);d.fillStyle="red";d.fillRect(3,3,this.health/this.baseHealth*18,2)},a.prototype.hit=function(a,
b){var c=1,d=0,f=" HP";a.spell===this.spell?(c=0,f=" HP *IMMUNE*"):a.spell===this.weakTo&&(c=2,f=" HP *CRIT!*");d=c*a.strength;this.health-=d;b(2===c,d,"-"+d+f)},a.prototype.update=function(a,b){this.stepTimer+=b;this.stepTimer>this.step&&(this.z-=a*b,this.stepTimer=0);this.attacking?(this.attackFor-=b,0>this.attackFor&&(this.attacking=!1)):this.lastAttacked+=b;0>=this.health&&(this.dead=!0)},a.prototype.render=function(a,b){var c=this.fov/(this.fov+this.z),f=this.x*c+a/2,q=this.y*c+b/2;200<this.z||
this.dead||(d.globalAlpha=1-this.z/200,d.drawImage(this.image,f-this.w*c/2,q-(this.attacking?2:0)-this.h*c/2,this.w*c,this.h*c),d.globalAlpha=1,t&&(this.drawHealthMeter(),d.fillStyle="white",d.fillRect(a/2-15,b-9,30,7),d.fillStyle="black",d.fillRect(a/2-14,b-8,28,5)))},a}();u=function(a){var c=r.randInt;return{x:2,y:2,w:76,h:48,stats:null,player:null,enemy:null,texts:[],init:function(){this.pos=0;this.vel=1E3;this.player=this.stats=null;this.spawnPlayer();this.enemy=null;this.spawnEnemy();this.bg=
p.bg},spawnPlayer:function(){this.player=new $},spawnEnemy:function(){var a=new S({level:this.player.level});if(this.enemy&&this.enemy.type===a.type)return this.spawnEnemy();this.enemy=a},hitPlayer:function(){var a=this,d=this.player.hit({strength:this.enemy.strength,critChance:this.enemy.critChance});w.remove(d.damage,function(c){d.crit&&a.texts.push(new E({x:118,y:78,dY:1,text:"*CRIT!*"}));a.texts.push(new E({x:118,y:88,dY:1,text:c}));a.player.stats.update("mostDamageTaken",{amount:d.damage,enemy:a.enemy.name});
a.player.stats.update("damageTakenOverall",a.player.stats.damageTakenOverall+d.damage)});H.play(c(0,1)?"thud":this.enemy.name);this.enemy.lastAttacked=0;this.enemy.attacking=!0;this.enemy.attackFor=.5},hitEnemy:function(a,d,g){var f=this;this.enemy.hit({spell:d.spell,strength:g},function(a,b,d){f.texts.push(new E({x:9,y:20,dY:1,text:d}));a?(f.player.stats.update("highestCrit",{amount:b,enemy:f.enemy.name}),f.hitPlayer()):c(0,2)||f.hitPlayer()});H.play(d.spell)},castSpell:function(a){this.player.castAnimation();
this.player.stats.update("longestSpellChain",a)},gainTime:function(a){var c=this;w.add(a,function(a){c.texts.push(new E({x:118,y:88,dY:1,text:a}))})},update:function(a){this.checkTimer()||(this.vel=t?0:1E3,this.pos+=this.vel,this.player.update(a),5>this.enemy.z&&(t=!0),this.enemy.dead?(this.spawnEnemy(),this.player.level+=1.4,this.player.stats.update("totalEnemiesKilled",this.player.stats.totalEnemiesKilled+1),t=!1):(t&&8<this.enemy.lastAttacked&&this.hitPlayer(),this.enemy.update(this.vel,a)))},
render:function(){var a;d.save();d.scale(4,4);d.translate(this.x,this.y);h.fillRect({c:"gray",x:0,y:0,w:this.w,h:this.h});d.rect(1,1,this.w-2,this.h-2);d.clip();d.drawImage(this.bg,0,0);this.enemy.render(this.w,this.h);this.player.render();d.restore();d.save();d.scale(2,2);for(a=0;a<this.texts.length;a++)this.texts[a].render();t&&h.drawText({text:this.enemy.name.toUpperCase(),x:2*(this.x+this.w/2)-this.enemy.name.length/2*4.3,y:2*(this.y+this.h-7)});d.restore()},checkTimer:function(){if(w.time>=w.maxTime)return this.player.stats.update("totalTimeSurvived",
(+new Date-w.startTime)/1E3|0),this.stats=this.player.stats,event=new CustomEvent("gameEnd"),a.dispatchEvent(event),this.player=null,!0}}}(document);T=function(){function a(a){this.x=a.x;this.y=a.y;this.size=1;this.vel={x:c(-1,1),y:a.vel.y};this.gravity={x:a.gravity.x,y:a.gravity.y};this.colour=a.colour;this.alpha=a.alpha;this.lifeSpan=c(this.minLife,this.minLife+this.lifeRange);this.dead=!1}var c=r.rand;return a.prototype.update=function(a){this.vel.x+=this.gravity.x*a;this.vel.y+=this.gravity.y*
a;this.x+=this.vel.x*a;this.y+=this.vel.y*a;this.lifeSpan-=a;0>this.lifeSpan&&(this.dead=!0)},a.prototype.render=function(){h.fillRect({c:"rgba(255, 255, 255,"+this.alpha+")",c:this.colour,x:this.x,y:this.y,w:this.size,h:this.size})},a}();L=function(){return{particles:[],create:function(a,c){var b;for(b=0;b<c;b++)this.particles.push(new T(type))},update:function(a){var c;for(c=0;c<this.particles.length;c++)this.particles[c].update(a)},render:function(){var a;for(a=0;a<this.particles.length;a++)this.particles[a].render()}}}();
U=function(){var a="ontouchstart"in window;return{title:function(){d.save();d.scale(4,4);h.drawText({text:"Tiny Dungeon",x:13.5,y:12});h.drawText({text:(a?"Tap":"Click")+" To Start",x:a?14:12.5,y:102});L.render();d.drawImage(p.s_title,18,36);d.restore()},game:function(){u.render();s.render();w.render()},social:function(){var a=u.stats;d.save();d.scale(4,4);h.drawText({text:"You survived",x:13.5,y:12});h.drawText({text:"for "+a.totalTimeSurvived+" seconds",x:12-2*(""+a.totalTimeSurvived).length,y:22});
h.drawText({text:"in the",x:28,y:32});h.drawText({text:"Tiny Dungeon",x:13.5,y:42});d.fillStyle="#00B0ED";d.fillRect(2,59,37,15);h.drawText({text:"Tweet",x:8.5,y:64});d.fillStyle="#3B5998";d.fillRect(41,59,37,15);h.drawText({text:"Share",x:48,y:64});d.fillStyle="green";d.fillRect(2,76,76,15);h.drawText({text:"Play Again",x:18,y:81});h.drawText({text:"   Enemies killed: "+a.totalEnemiesKilled+"   Longest spell chain: "+a.longestSpellChain+"   Highest critical strike: "+a.highestCrit.amount+" on "+
a.highestCrit.enemy+"   Most damage taken: "+a.mostDamageTaken.amount+" from "+a.mostDamageTaken.enemy+"   Damage taken overall: "+a.damageTakenOverall,x:80-this.statsX,y:103});this.statsX+=.3;800<this.statsX&&(this.statsX=0);d.restore()},statsX:0}}();V=function(){function a(){this.frame=this.frame.bind(this);this.lastTime=0;this.callback=function(){};this.start=function(a){this.callback=a;requestAnimationFrame(this.frame)}}return a.prototype.frame=function(a){var b=(a-this.lastTime)/1E3;this.lastTime=
a;.2>b&&this.callback(b);requestAnimationFrame(this.frame)},new a}();m=function(a,c){return{currentTile:{},chain:[],firstInChain:function(a){(a=s.getTileAtScreenPos(a))&&(a=s.getTileAtCell(a),a&&(a.selected=!0,this.chain.push(a),this.currentTile=a))},nextInChain:function(a){var c=s.getTileAtScreenPos(a),d,f;c&&(c=s.getTileAtCell(c),c&&c!==this.currentTile&&c.type===this.currentTile.type&&s.validMove(this.currentTile,c)&&(d=this.chain.filter(function(a){return c===a}),d.length&&(f=this.chain.indexOf(d[0]),
d=this.chain.splice(f,this.chain.length-f),d.forEach(function(a){a.selected=!1})),c.selected=!0,this.chain.push(c),this.currentTile=c))},lastInChain:function(){1<this.chain.length?(this.chain.forEach(function(a){s.removeTileAt({x:a.x,y:a.y})}),u.castSpell(this.chain.length),t?u.hitEnemy({x:s.x,y:s.y},this.currentTile,this.chain.length):u.gainTime(this.chain.length/2),s.replaceMatchedTiles()):this.chain[0]&&(this.chain[0].selected=!1);this.chain=[]},init:function(){var a;H.init();K.init();h.init();
L.create({name:"fire",x:15,y:12});a=new CustomEvent("gameReady");c.dispatchEvent(a)},ready:function(){V.start(function(a){d.clearRect(0,0,320,480);u.player&&(u.update(a),s.update(a),L.update(a),w.update(a),f.update());U[z]()})},start:function(){z="game";document.querySelector(".social").style.display="none";w=new Y;w.init();t=!1;s.init();u.init()},pause:function(a){"game"===z&&(a&&H.play("stun"),w.pause(a))},end:function(){var a="I survived for "+u.stats.totalTimeSurvived+" seconds in the Tiny Dungeon http://js13kgames.com/entries/tiny-dungeon/";
z="social";U.statsX=0;document.querySelector(".tweet").href="https://twitter.com/intent/tweet?text="+encodeURIComponent(a)+"&hashtags=js13k";"_blank";document.querySelector(".share").href="http://www.facebook.com/sharer.php?s=100&p[title]=Tiny+Dungeon+js13k+Game&p[url]="+encodeURIComponent("http://js13kgames.com/entries/tiny-dungeon/")+"&p[summary]="+encodeURIComponent(a+" #js13k");"_blank";document.querySelector(".social").style.display="block"}}}(window,document);A=function(a,c){var b={},d={init:function(){this.bind("start",
m.start);this.bind("pause",m.pause);this.bind("firstInChain",m.firstInChain);this.bind("nextInChain",m.nextInChain);this.bind("lastInChain",m.lastInChain)},bind:function(a,c){b[a]||(b[a]=[]);b[a].push(c)},trigger:function(a,c){var d=b[a],e=Array.prototype.slice.call(arguments,1),f,h;if(d)for(f=d.length,h=0;h<f;h++)d[h].apply(m,e)}};return d.init(),d}();(function(a,c){function b(a,b){var c,d;if(f&&a.touches){if(a.touches.length>b)return;c=a[b?"touches":"changedTouches"][0].clientX;d=a[b?"touches":
"changedTouches"][0].clientY}else c=a.clientX,d=a.clientY;return{x:c,y:d}}var d=!1,f="ontouchstart"in window,h={init:function(){var a=this;this.bind(c,"DOMContentLoaded",r.loadAllAssets.call(r));this.bind(c,"imagesLoaded",m.init);this.bind(c,"gameReady",m.ready);this.bind(c,"gameEnd",m.end);this.bind(c,"mousedown touchstart",function(a){var c=b(a,1);"title"===z?A.trigger("start"):"game"===z&&(A.trigger("firstInChain",{x:c.x,y:c.y}),d=!0,a.preventDefault())});this.bind(c,"mousemove touchmove",function(a){var c=
b(a,1);"game"===z&&(d&&A.trigger("nextInChain",{x:c.x,y:c.y}),a.preventDefault())});this.bind(c,"mouseup touchend",function(a){var c=b(a,0);"game"===z&&(A.trigger("lastInChain",{x:c.x,y:c.y}),d=!1,a.preventDefault())});this.bind(document.querySelector(".again"),"mousedown touchstart",function(a){A.trigger("start");a.preventDefault()});(function(){["webkit","moz","ms",""].forEach(function(b,d){b+"Hidden"in c&&a.bind(c,b+"visibilitychange",function(a){A.trigger("pause",!!c[b+"Hidden"])})})})()},bind:function(a,
b,c){"string"==typeof a&&(a=document.querySelector(a));0<=b.indexOf(" ")?b=b.split(" "):b=[b];b.forEach(function(b){a.addEventListener(b,c,!1)})}};return h.init(),h})(window,document)})();
